<!doctype html>
<html lang="en" data-theme="light">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Pure YAML Config File - No HTML</title>
    <style>
      body {
        max-width: 880px;
        margin: 0 auto;
        padding: 32px 80px;
        position: relative;
        box-sizing: border-box;
        font-family: 'Times New Roman', serif;
        line-height: 1.6;
        color: #000;
        background: #fff;
      }

      .code-block {
        background: #f8f8f8;
        border: 1px solid #ddd;
        padding: 20px;
        font-family: 'Courier New', monospace;
        font-size: 14px;
        line-height: 1.4;
        white-space: pre-wrap;
        word-wrap: break-word;
        margin: 20px 0;
      }

      .warning {
        background: #fff3cd;
        border: 1px solid #ffeaa7;
        padding: 15px;
        margin: 20px 0;
        border-left: 4px solid #f39c12;
      }

      .instructions {
        background: #d4edda;
        border: 1px solid #c3e6cb;
        padding: 15px;
        margin: 20px 0;
        border-left: 4px solid #28a745;
      }
    </style>
  </head>
  <body>
    <h1>Pure YAML Config File - No HTML</h1>

    <div class="warning">
      <strong>Important:</strong> This is a pure YAML configuration file. Copy ONLY the YAML content below (not the
      HTML) into your config.yml file.
    </div>

    <h2>File: config.yml</h2>

    <div class="instructions">
      <strong>Instructions:</strong>
      <br />1. Copy the YAML content below (everything in the gray box) <br />2. Create a new file called "config.yml"
      in your /admin/ folder <br />3. Paste the YAML content into the file <br />4. Make sure there are NO HTML tags in
      your config.yml file <br />5. Save the file with .yml extension (not .html)
    </div>

    <div class="code-block">
      backend: name: git-gateway branch: main media_folder: "images/uploads" public_folder: "/images/uploads"
      collections: - name: "news" label: "News Articles" folder: "_posts/news" create: true slug:
      "{{year}}-{{month}}-{{day}}-{{slug}}" fields: - {label: "Title", name: "title", widget: "string"} - {label:
      "Publish Date", name: "date", widget: "datetime"} - {label: "Author", name: "author", widget: "string"} - {label:
      "Category", name: "category", widget: "select", options: ["Breaking News", "Market Analysis", "Regulation",
      "Technology", "Regional"]} - {label: "Region", name: "region", widget: "select", options: ["Japan", "China",
      "South Korea", "Singapore", "Hong Kong", "Southeast Asia", "General"]} - {label: "Featured Image", name: "image",
      widget: "image"} - {label: "Excerpt", name: "excerpt", widget: "text"} - {label: "Body", name: "body", widget:
      "markdown"} - {label: "Tags", name: "tags", widget: "list"} - {label: "SEO Title", name: "seo_title", widget:
      "string", required: false} - {label: "SEO Description", name: "seo_description", widget: "text", required: false}
      - name: "education" label: "Education" folder: "_posts/education" create: true slug:
      "{{year}}-{{month}}-{{day}}-{{slug}}" fields: - {label: "Title", name: "title", widget: "string"} - {label:
      "Publish Date", name: "date", widget: "datetime"} - {label: "Author", name: "author", widget: "string"} - {label:
      "Difficulty Level", name: "difficulty", widget: "select", options: ["Beginner", "Intermediate", "Advanced"]} -
      {label: "Topic", name: "topic", widget: "select", options: ["Basics", "Security", "Trading", "AI", "Blockchain",
      "Wallets"]} - {label: "Featured Image", name: "image", widget: "image"} - {label: "Excerpt", name: "excerpt",
      widget: "text"} - {label: "Body", name: "body", widget: "markdown"} - {label: "Tags", name: "tags", widget:
      "list"} - name: "market-analysis" label: "Market Analysis" folder: "_posts/market-analysis" create: true slug:
      "{{year}}-{{month}}-{{day}}-{{slug}}" fields: - {label: "Title", name: "title", widget: "string"} - {label:
      "Publish Date", name: "date", widget: "datetime"} - {label: "Author", name: "author", widget: "string"} - {label:
      "Analysis Type", name: "analysis_type", widget: "select", options: ["Daily Report", "Weekly Outlook", "Technical
      Analysis", "Fundamental Analysis"]} - {label: "Cryptocurrencies", name: "cryptocurrencies", widget: "list"} -
      {label: "Featured Image", name: "image", widget: "image"} - {label: "Excerpt", name: "excerpt", widget: "text"} -
      {label: "Body", name: "body", widget: "markdown"} - {label: "Tags", name: "tags", widget: "list"} - name:
      "authors" label: "Authors" folder: "_authors" create: true slug: "{{slug}}" fields: - {label: "Name", name:
      "name", widget: "string"} - {label: "Email", name: "email", widget: "string"} - {label: "Bio", name: "bio",
      widget: "text"} - {label: "Avatar", name: "avatar", widget: "image"} - {label: "Twitter", name: "twitter", widget:
      "string", required: false} - {label: "LinkedIn", name: "linkedin", widget: "string", required: false} - {label:
      "Website", name: "website", widget: "string", required: false} - name: "pages" label: "Pages" files: - label:
      "About Page" name: "about" file: "_pages/about.md" fields: - {label: "Title", name: "title", widget: "string"} -
      {label: "Body", name: "body", widget: "markdown"} - label: "Contact Page" name: "contact" file:
      "_pages/contact.md" fields: - {label: "Title", name: "title", widget: "string"} - {label: "Body", name: "body",
      widget: "markdown"}
    </div>

    <h2>File Structure Required</h2>

    <p>Make sure your repository has this folder structure:</p>

    <div class="code-block">
      your-website-root/ ├── admin/ │ ├── index.html │ └── config.yml (←← This file contains the YAML above) ├── _posts/
      │ ├── news/ │ ├── education/ │ └── market-analysis/ ├── _authors/ ├── _pages/ └── images/ └── uploads/
    </div>

    <div class="warning">
      <strong>Critical:</strong> The config.yml file must contain ONLY the YAML content above. No HTML tags, no DOCTYPE,
      no extra formatting. Just pure YAML text.
    </div>

    <h2>Next Steps</h2>

    <p>After creating the pure YAML config.yml file:</p>

    <ol>
      <li>Upload both admin/index.html and admin/config.yml to your repository</li>
      <li>Enable Git Gateway in your Netlify dashboard</li>
      <li>Enable Identity in Netlify</li>
      <li>Test the admin interface at asiacryptonews.com/admin/</li>
    </ol>

    <p>
      This configuration will resolve the YAML syntax errors and provide you with a fully functional content management
      system for your Asia Crypto News website.
    </p>
  <script defer src="https://static.cloudflareinsights.com/beacon.min.js/vcd15cbe7772f49c399c6a5babf22c1241717689176015" integrity="sha512-ZpsOmlRQV6y907TI0dKBHq9Md29nnaEIPlkf84rnaERnq6zvWvPUqr2ft8M1aS28oN72PdrCzSjY4U6VaAw1EQ==" data-cf-beacon='{"rayId":"95d70e60dadfe2f5","serverTiming":{"name":{"cfExtPri":true,"cfEdge":true,"cfOrigin":true,"cfL4":true,"cfSpeedBrain":true,"cfCacheStatus":true}},"version":"2025.6.2","token":"4edd5f8ec12a48cfa682ab8261b80a79"}' crossorigin="anonymous"></script>
</body>
</html>

    <script id="html_badge_script1">
        window.__genspark_remove_badge_link = "https://www.genspark.ai/api/html_badge/" +
            "remove_badge?token=To%2FBnjzloZ3UfQdcSaYfDlaEVPmzM%2Ba6TNCfJL%2Fj1VI9%2F67bE3RFgZzpv4W9EkMVTLtvT8U3fdZsdyg4bt2HoCGYQMqv6x%2FMlSVOFFwcWWvI8EWJQg5PKrah2EJOwP%2FjcvV1DkZcaunRicE%2Bn%2Fukv%2FXI1niE7h4KHRQYY2qwlhE6jkewMSJOgrkGK4UxadZrvVq%2Fwsb2%2FfNLfFVqtTdt1UPotGnngF4Tr8eyTLxLT7WYjq7dgbU3qfNmwFlB%2FBPaCDkZyUNlynWSDiNhnjykYm5q5Ig4htW5NlHFoyGtAtjbxnNnZlQrILfvS2y4O4z7J%2F8s%2FRCU3QvihBUxIDfK1euY8G%2FDHhxyau%2FaNXnEWnwQiIMYozUMg6qQ0m6dAzzWSG0P9G9E77OrUa3SEoq3zFePLQTPnnvUOGbpVDajlsrX23QskJgW%2Fpy5%2BJIBgg6Qhgs7gpdWti7y27kyYifK8lSQl5tqoDCqbVjpffsHMTZKQyDJe%2B%2FdnhN8mqG0myTzW2NCpbmqyMGrjNhNOlMtaA%3D%3D";
        window.__genspark_locale = "en-US";
        window.__genspark_token = "To/BnjzloZ3UfQdcSaYfDlaEVPmzM+a6TNCfJL/j1VI9/67bE3RFgZzpv4W9EkMVTLtvT8U3fdZsdyg4bt2HoCGYQMqv6x/MlSVOFFwcWWvI8EWJQg5PKrah2EJOwP/jcvV1DkZcaunRicE+n/ukv/XI1niE7h4KHRQYY2qwlhE6jkewMSJOgrkGK4UxadZrvVq/wsb2/fNLfFVqtTdt1UPotGnngF4Tr8eyTLxLT7WYjq7dgbU3qfNmwFlB/BPaCDkZyUNlynWSDiNhnjykYm5q5Ig4htW5NlHFoyGtAtjbxnNnZlQrILfvS2y4O4z7J/8s/RCU3QvihBUxIDfK1euY8G/DHhxyau/aNXnEWnwQiIMYozUMg6qQ0m6dAzzWSG0P9G9E77OrUa3SEoq3zFePLQTPnnvUOGbpVDajlsrX23QskJgW/py5+JIBgg6Qhgs7gpdWti7y27kyYifK8lSQl5tqoDCqbVjpffsHMTZKQyDJe+/dnhN8mqG0myTzW2NCpbmqyMGrjNhNOlMtaA==";
    </script>
    
    <script id="html_notice_dialog_script" src="https://www.genspark.ai/notice_dialog.js"></script>
    