backend:
  name: github
  repo: brianking74/asia-crypto-news
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name:   "news"
    label:  "News Articles"
    folder: "_posts/news"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Category", name: "category", widget: "select", options: ["Breaking News", "Market Analysis", "Regulation"]}
  
  - name:   "education"
    label:  "Educational Content"
    folder: "_posts/education"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
