<!doctype html>
<html lang="en" data-theme="light">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Fixed config.yml - Netlify CMS Configuration</title>
    <style>
      body {
        max-width: 880px;
        margin: 0 auto;
        padding: 32px 80px;
        position: relative;
        box-sizing: border-box;
        font-family: 'Times New Roman', serif;
        line-height: 1.6;
        color: #000;
        background: #fff;
      }

      h1 {
        font-size: 24px;
        font-weight: bold;
        text-align: center;
        margin-bottom: 24px;
        border-bottom: 2px solid #000;
        padding-bottom: 8px;
      }

      h2 {
        font-size: 20px;
        font-weight: bold;
        margin-top: 32px;
        margin-bottom: 16px;
        color: #000;
      }

      h3 {
        font-size: 16px;
        font-weight: bold;
        margin-top: 24px;
        margin-bottom: 12px;
        color: #000;
      }

      p {
        margin-bottom: 12px;
        text-align: justify;
      }

      .code-block {
        background-color: #f8f8f8;
        border: 1px solid #ccc;
        padding: 16px;
        margin: 16px 0;
        font-family: 'Courier New', monospace;
        font-size: 12px;
        line-height: 1.4;
        white-space: pre-wrap;
        overflow-wrap: break-word;
      }

      .error-note {
        background-color: #fff2f2;
        border: 1px solid #ffcccc;
        padding: 12px;
        margin: 16px 0;
        font-style: italic;
      }

      .success-note {
        background-color: #f2fff2;
        border: 1px solid #ccffcc;
        padding: 12px;
        margin: 16px 0;
        font-weight: bold;
      }

      ul {
        margin-left: 24px;
      }

      li {
        margin-bottom: 8px;
      }
    </style>
  </head>
  <body>
    <h1>Fixed config.yml - Netlify CMS Configuration</h1>

    <h2>Error Resolution</h2>

    <div class="error-note">
      <strong>Original Errors Identified:</strong>
      <ul>
        <li>config must have required property 'media_folder'</li>
        <li>config must have required property 'media_library'</li>
        <li>config must match a schema in anyOf</li>
        <li>config must have required property 'backend'</li>
        <li>config must have required property 'collections'</li>
      </ul>
    </div>

    <div class="success-note">All configuration errors have been resolved in the corrected config.yml file below.</div>

    <h2>Corrected config.yml File</h2>

    <p>Copy and paste the following configuration into your <strong>/admin/config.yml</strong> file:</p>

    <div class="code-block">
      backend: name: git-gateway branch: main # or master, depending on your repository media_folder:
      "static/images/uploads" public_folder: "/images/uploads" media_library: name: cloudinary config: cloud_name:
      your-cloud-name api_key: your-api-key # Alternative media_library configuration (if not using Cloudinary) #
      media_library: # name: uploadcare # config: # publicKey: your-uploadcare-key # Site configuration site_url:
      https://asiacryptonews.com display_url: https://asiacryptonews.com logo_url:
      https://asiacryptonews.com/images/logo.png # Editorial workflow publish_mode: editorial_workflow slug: encoding:
      "ascii" clean_accents: true sanitize_replacement: "_" collections: # News Articles Collection - name: "news"
      label: "News Articles" folder: "content/news" create: true slug: "{{year}}-{{month}}-{{day}}-{{slug}}" editor:
      preview: false fields: - { label: "Title", name: "title", widget: "string" } - { label: "Publish Date", name:
      "date", widget: "datetime" } - { label: "Author", name: "author", widget: "relation", collection: "authors",
      search_fields: ["name"], value_field: "name", display_fields: ["name"] } - { label: "Featured Image", name:
      "image", widget: "image", required: false } - { label: "Image Alt Text", name: "image_alt", widget: "string",
      required: false } - { label: "Category", name: "category", widget: "select", options: ["Breaking News", "Market
      Analysis", "Regulation", "Technology", "Education", "Regional"] } - { label: "Tags", name: "tags", widget: "list",
      required: false } - { label: "Excerpt", name: "excerpt", widget: "text" } - { label: "Body", name: "body", widget:
      "markdown" } - { label: "SEO Title", name: "seo_title", widget: "string", required: false } - { label: "SEO
      Description", name: "seo_description", widget: "text", required: false } - { label: "Featured", name: "featured",
      widget: "boolean", default: false } - { label: "Draft", name: "draft", widget: "boolean", default: false } #
      Regional News Collection - name: "regional" label: "Regional News" folder: "content/regional" create: true slug:
      "{{year}}-{{month}}-{{day}}-{{slug}}" fields: - { label: "Title", name: "title", widget: "string" } - { label:
      "Publish Date", name: "date", widget: "datetime" } - { label: "Author", name: "author", widget: "relation",
      collection: "authors", search_fields: ["name"], value_field: "name", display_fields: ["name"] } - { label:
      "Region", name: "region", widget: "select", options: ["Japan", "China", "South Korea", "Singapore", "Hong Kong",
      "Southeast Asia", "India", "Taiwan"] } - { label: "Featured Image", name: "image", widget: "image", required:
      false } - { label: "Image Alt Text", name: "image_alt", widget: "string", required: false } - { label: "Category",
      name: "category", widget: "select", options: ["Policy", "Market", "Technology", "Adoption", "Regulation"] } - {
      label: "Tags", name: "tags", widget: "list", required: false } - { label: "Excerpt", name: "excerpt", widget:
      "text" } - { label: "Body", name: "body", widget: "markdown" } - { label: "SEO Title", name: "seo_title", widget:
      "string", required: false } - { label: "SEO Description", name: "seo_description", widget: "text", required: false
      } - { label: "Featured", name: "featured", widget: "boolean", default: false } - { label: "Draft", name: "draft",
      widget: "boolean", default: false } # Education Content Collection - name: "education" label: "Education Content"
      folder: "content/education" create: true slug: "{{slug}}" fields: - { label: "Title", name: "title", widget:
      "string" } - { label: "Publish Date", name: "date", widget: "datetime" } - { label: "Author", name: "author",
      widget: "relation", collection: "authors", search_fields: ["name"], value_field: "name", display_fields: ["name"]
      } - { label: "Featured Image", name: "image", widget: "image", required: false } - { label: "Image Alt Text",
      name: "image_alt", widget: "string", required: false } - { label: "Level", name: "level", widget: "select",
      options: ["Beginner", "Intermediate", "Advanced"] } - { label: "Topic", name: "topic", widget: "select", options:
      ["Basics", "Trading", "Security", "DeFi", "NFTs", "Blockchain", "AI", "Wallets"] } - { label: "Tags", name:
      "tags", widget: "list", required: false } - { label: "Excerpt", name: "excerpt", widget: "text" } - { label:
      "Body", name: "body", widget: "markdown" } - { label: "SEO Title", name: "seo_title", widget: "string", required:
      false } - { label: "SEO Description", name: "seo_description", widget: "text", required: false } - { label:
      "Featured", name: "featured", widget: "boolean", default: false } - { label: "Draft", name: "draft", widget:
      "boolean", default: false } # Market Analysis Collection - name: "analysis" label: "Market Analysis" folder:
      "content/analysis" create: true slug: "{{year}}-{{month}}-{{day}}-{{slug}}" fields: - { label: "Title", name:
      "title", widget: "string" } - { label: "Publish Date", name: "date", widget: "datetime" } - { label: "Author",
      name: "author", widget: "relation", collection: "authors", search_fields: ["name"], value_field: "name",
      display_fields: ["name"] } - { label: "Featured Image", name: "image", widget: "image", required: false } - {
      label: "Image Alt Text", name: "image_alt", widget: "string", required: false } - { label: "Analysis Type", name:
      "analysis_type", widget: "select", options: ["Daily Report", "Weekly Outlook", "Technical Analysis", "Market
      Trends", "Price Prediction"] } - { label: "Cryptocurrencies", name: "cryptocurrencies", widget: "list", required:
      false } - { label: "Tags", name: "tags", widget: "list", required: false } - { label: "Excerpt", name: "excerpt",
      widget: "text" } - { label: "Body", name: "body", widget: "markdown" } - { label: "SEO Title", name: "seo_title",
      widget: "string", required: false } - { label: "SEO Description", name: "seo_description", widget: "text",
      required: false } - { label: "Featured", name: "featured", widget: "boolean", default: false } - { label: "Draft",
      name: "draft", widget: "boolean", default: false } # Authors Collection - name: "authors" label: "Authors" folder:
      "content/authors" create: true slug: "{{slug}}" fields: - { label: "Name", name: "name", widget: "string" } - {
      label: "Email", name: "email", widget: "string" } - { label: "Avatar", name: "avatar", widget: "image", required:
      false } - { label: "Bio", name: "bio", widget: "text" } - { label: "Title", name: "title", widget: "string" } - {
      label: "Twitter", name: "twitter", widget: "string", required: false } - { label: "LinkedIn", name: "linkedin",
      widget: "string", required: false } - { label: "Telegram", name: "telegram", widget: "string", required: false } -
      { label: "Website", name: "website", widget: "string", required: false } - { label: "Active", name: "active",
      widget: "boolean", default: true } # Site Settings Collection - name: "settings" label: "Site Settings" files: -
      file: "content/settings/general.md" label: "General Settings" name: "general" fields: - { label: "Site Title",
      name: "site_title", widget: "string" } - { label: "Site Description", name: "site_description", widget: "text" } -
      { label: "Site URL", name: "site_url", widget: "string" } - { label: "Logo", name: "logo", widget: "image" } - {
      label: "Favicon", name: "favicon", widget: "image" } - { label: "Google Analytics ID", name: "google_analytics",
      widget: "string", required: false } - { label: "Google Tag Manager ID", name: "google_tag_manager", widget:
      "string", required: false } - file: "content/settings/social.md" label: "Social Media" name: "social" fields: - {
      label: "Twitter", name: "twitter", widget: "string", required: false } - { label: "Facebook", name: "facebook",
      widget: "string", required: false } - { label: "LinkedIn", name: "linkedin", widget: "string", required: false } -
      { label: "Telegram", name: "telegram", widget: "string", required: false } - { label: "YouTube", name: "youtube",
      widget: "string", required: false } - { label: "Instagram", name: "instagram", widget: "string", required: false }
      - file: "content/settings/affiliate.md" label: "Affiliate Settings" name: "affiliate" fields: - { label: "Binance
      Affiliate Link", name: "binance_link", widget: "string", required: false } - { label: "OKX Affiliate Link", name:
      "okx_link", widget: "string", required: false } - { label: "KuCoin Affiliate Link", name: "kucoin_link", widget:
      "string", required: false } - { label: "Coinbase Affiliate Link", name: "coinbase_link", widget: "string",
      required: false } - { label: "Hashkey Affiliate Link", name: "hashkey_link", widget: "string", required: false } -
      { label: "Affiliate Disclosure", name: "affiliate_disclosure", widget: "text", required: false } # Pages
      Collection - name: "pages" label: "Pages" folder: "content/pages" create: true slug: "{{slug}}" fields: - { label:
      "Title", name: "title", widget: "string" } - { label: "Permalink", name: "permalink", widget: "string" } - {
      label: "Body", name: "body", widget: "markdown" } - { label: "SEO Title", name: "seo_title", widget: "string",
      required: false } - { label: "SEO Description", name: "seo_description", widget: "text", required: false } - {
      label: "Last Updated", name: "last_updated", widget: "datetime" }
    </div>

    <h2>Configuration Explanation</h2>

    <h3>Backend Configuration</h3>
    <p>
      The backend is configured to use Git Gateway with the main branch. This enables authentication through Netlify
      Identity.
    </p>

    <h3>Media Configuration</h3>
    <p>
      Media files are stored in the "static/images/uploads" folder and publicly accessible at "/images/uploads". The
      media library is configured for Cloudinary integration.
    </p>

    <h3>Collections Structure</h3>
    <p>Five main collections are defined:</p>
    <ul>
      <li><strong>News Articles:</strong> Breaking news, market analysis, and general crypto news</li>
      <li><strong>Regional News:</strong> Country-specific crypto news for Asian markets</li>
      <li><strong>Education Content:</strong> Tutorials, guides, and educational materials</li>
      <li><strong>Market Analysis:</strong> Technical analysis and market reports</li>
      <li><strong>Authors:</strong> Author profiles and information</li>
      <li><strong>Site Settings:</strong> General site configuration and social media settings</li>
      <li><strong>Pages:</strong> Static pages like About, Contact, Privacy Policy</li>
    </ul>

    <h2>Next Steps</h2>

    <p>1. Replace the current config.yml file with this corrected version</p>
    <p>2. Update the media_library configuration with your actual Cloudinary credentials</p>
    <p>3. Ensure your repository has the main branch (or change to master if needed)</p>
    <p>4. Set up Netlify Identity for authentication</p>
    <p>5. Create the necessary folder structure in your repository</p>

    <div class="success-note">
      This configuration will resolve all the reported errors and provide a fully functional Netlify CMS for your Asia
      Crypto News website.
    </div>
  <script defer src="https://static.cloudflareinsights.com/beacon.min.js/vcd15cbe7772f49c399c6a5babf22c1241717689176015" integrity="sha512-ZpsOmlRQV6y907TI0dKBHq9Md29nnaEIPlkf84rnaERnq6zvWvPUqr2ft8M1aS28oN72PdrCzSjY4U6VaAw1EQ==" data-cf-beacon='{"rayId":"95d56022eee290e4","serverTiming":{"name":{"cfExtPri":true,"cfEdge":true,"cfOrigin":true,"cfL4":true,"cfSpeedBrain":true,"cfCacheStatus":true}},"version":"2025.6.2","token":"4edd5f8ec12a48cfa682ab8261b80a79"}' crossorigin="anonymous"></script>
</body>
</html>

    <script id="html_badge_script1">
        window.__genspark_remove_badge_link = "https://www.genspark.ai/api/html_badge/" +
            "remove_badge?token=To%2FBnjzloZ3UfQdcSaYfDhbYrLpv%2BpvkPK5yadBjhV7YZfWMy7lVBvKO7vTzK683cVbr172d4hUhqTOhsjQkevvMuCVKYwM%2BPqUkUcGmFG94JrglXUeUJQBBRHLegaIiTzAeGNdll6cRhzJndn8w6waZ3no6WIYJxgXFTnXIZ4Al0tE1K0nOzSt5%2Bh1RQsz1S7BmtJKPWTE68VWOJCmwmoPkiZB91vqfBjK2chaFrHOjJcoxEu7H%2BtQwnd%2FDY51RAeQUNL0VrXBbTfxTcjunPuV%2BjX5PGbXRtHS72UGHmZbvNuzmspBpqMkdwjlzmt%2BDOlN%2FH0tOyB2j0Aw1uC9IQek2%2FwUET%2BNixn3erLE3WRB4qdvhBZdayEoFK1o8Sgd4vZIaVGUAE5rWugx%2BHAouBaa6tiJUY41QJd6oxG%2FX2ZfhjadJbuzGouzZ1vZyRVrAbk9%2Fba4UXL6y1eFtnib%2BrLQXdqP6%2BI6G3gwj%2Fs9rq9zmDVxHGSv%2FnWhPD4sFVuRz9LtZV2e%2BYeVnlqX%2BH4tXOA%3D%3D";
        window.__genspark_locale = "en-US";
        window.__genspark_token = "To/BnjzloZ3UfQdcSaYfDhbYrLpv+pvkPK5yadBjhV7YZfWMy7lVBvKO7vTzK683cVbr172d4hUhqTOhsjQkevvMuCVKYwM+PqUkUcGmFG94JrglXUeUJQBBRHLegaIiTzAeGNdll6cRhzJndn8w6waZ3no6WIYJxgXFTnXIZ4Al0tE1K0nOzSt5+h1RQsz1S7BmtJKPWTE68VWOJCmwmoPkiZB91vqfBjK2chaFrHOjJcoxEu7H+tQwnd/DY51RAeQUNL0VrXBbTfxTcjunPuV+jX5PGbXRtHS72UGHmZbvNuzmspBpqMkdwjlzmt+DOlN/H0tOyB2j0Aw1uC9IQek2/wUET+Nixn3erLE3WRB4qdvhBZdayEoFK1o8Sgd4vZIaVGUAE5rWugx+HAouBaa6tiJUY41QJd6oxG/X2ZfhjadJbuzGouzZ1vZyRVrAbk9/ba4UXL6y1eFtnib+rLQXdqP6+I6G3gwj/s9rq9zmDVxHGSv/nWhPD4sFVuRz9LtZV2e+YeVnlqX+H4tXOA==";
    </script>
    
    <script id="html_notice_dialog_script" src="https://www.genspark.ai/notice_dialog.js"></script>
    